services:
  keycloak:
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm

  dl-front:
    container_name: dl-front
    build:
      context: ./dl-front
      dockerfile: Dockerfile
      args:
        ENV_NAME: dev
    ports:
      - "5173:5173"
    networks:
      - desafio-login

  proxy:
    container_name: proxy-dl
    # image: proxy-dl:latest
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - desafio-login
