services:
  keycloak:
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpass
      KC_HOSTNAME: localhost
    # command: start --optimized
    command: start-dev --import-realm
    depends_on:
      - postgres

  dl-front:
    container_name: dl-front
    build:
      context: ./dl-front
      dockerfile: Dockerfile
      args:
        ENV_NAME: prod
    ports:
      - "5173:5173"
    networks:
      - desafio-login

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - desafio-login

  proxy:
    container_name: proxy-dl
    # image: proxy-dl:latest
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - desafio-login

volumes:
  postgres_data:
